# Generated by Django 4.2.2 on 2024-04-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default='DMY', max_length=15),
            preserve_default=False,
        ),
    ]
