# Generated by Django 4.2.2 on 2024-04-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfacultydocument',
            name='subject',
            field=models.TextField(default='dummy text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addstaffdocument',
            name='subject',
            field=models.TextField(default='dummy'),
            preserve_default=False,
        ),
    ]
