# Generated by Django 4.2.2 on 2024-04-08 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0004_alter_addfacultydocument_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addfacultydocument',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='addstaffdocument',
            name='date_added',
        ),
    ]
