# Generated by Django 4.2.2 on 2024-04-08 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0005_remove_addfacultydocument_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfacultydocument',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='addstaffdocument',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
