# Generated by Django 4.2.2 on 2024-04-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0006_addfacultydocument_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='addfacultydocument',
            name='upload_file',
        ),
        migrations.RemoveField(
            model_name='addstaffdocument',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='addfacultydocument',
            name='upload_files',
            field=models.ManyToManyField(to='file_app.uploadedfile'),
        ),
        migrations.AddField(
            model_name='addstaffdocument',
            name='upload_files',
            field=models.ManyToManyField(to='file_app.uploadedfile'),
        ),
    ]
