# Generated by Django 4.2.2 on 2024-04-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0007_uploadedfile_remove_addfacultydocument_upload_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addfacultydocument',
            name='upload_files',
        ),
        migrations.RemoveField(
            model_name='addstaffdocument',
            name='upload_files',
        ),
        migrations.AddField(
            model_name='addfacultydocument',
            name='file_upload',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='addstaffdocument',
            name='file_upload',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
