# Generated by Django 4.2.2 on 2024-04-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0010_document_documentfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfile',
            name='document',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentFile',
        ),
    ]
