# Generated by Django 4.2.2 on 2024-04-25 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0016_show_showphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showphoto',
            name='show',
        ),
        migrations.DeleteModel(
            name='Show',
        ),
        migrations.DeleteModel(
            name='ShowPhoto',
        ),
    ]
