# Generated by Django 4.2.2 on 2024-04-25 06:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0018_staffdocs_staffdocumentfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_app.campus')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='file_app.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_app.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='staffdocumentfile',
            name='staff_document',
        ),
        migrations.DeleteModel(
            name='StaffDocs',
        ),
        migrations.DeleteModel(
            name='StaffDocumentFile',
        ),
        migrations.AddField(
            model_name='facultydocs',
            name='file_uploads',
            field=models.ManyToManyField(related_name='faculty_documents', to='file_app.fileupload'),
        ),
    ]
