# Generated by Django 4.2.2 on 2024-04-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0019_facultydocs_fileupload_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyDocs',
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
