# Generated by Django 4.2.2 on 2024-04-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0021_archives_archivesfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentimage',
            name='document',
        ),
        migrations.RemoveField(
            model_name='facultydocument',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='facultydocument',
            name='department',
        ),
        migrations.RemoveField(
            model_name='facultydocument',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='facultyimage',
            name='faculty_document',
        ),
        migrations.RemoveField(
            model_name='staffdocument',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='staffdocument',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staffdocument',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staffimage',
            name='staff_document',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentImage',
        ),
        migrations.DeleteModel(
            name='FacultyDocument',
        ),
        migrations.DeleteModel(
            name='FacultyImage',
        ),
        migrations.DeleteModel(
            name='StaffDocument',
        ),
        migrations.DeleteModel(
            name='StaffImage',
        ),
    ]
